export class IWaterFood {
    id?: number;
    month: string;
    day: string;
    pool: string;
    percent_of_full_pool: string;
    less_than_six:string;
    seven_to_twelve:string;
    thirteen_or_more:string;
    habitat_standing:string;
    habitat_mowed:string;
    habitat_disced:string;
    habitat_unharv_corn:string;
    habitat_harv_corn:string;
    habitat_unharv_milo:string;
    habitat_harv_milo:string;
    habitat_unharv_beans:string;
    habitat_harv_beans:string;
    habitat_browse:string;
    ice_standing:string;
    ice_mowed:string;
    ice_disced:string;
    ice_unharv_corn:string;
    ice_harv_corn:string;
    ice_unharv_milo:string;
    ice_harv_milo:string;
    ice_unharv_beans:string;
    ice_harv_beans:string;
    ice_browse:string;
    notes:string;
    actions:string;
    response:string;
    year:string;
    time:string;
    fiscal_year:string;
}

export class WaterFood implements IWaterFood {
    id?: 0;
    month:'';
    day: '';
    pool: '';
    percent_of_full_pool: '';
    less_than_six:'';
    seven_to_twelve:'';
    thirteen_or_more:'';
    habitat_standing:'';
    habitat_mowed:'';
    habitat_disced:'';
    habitat_unharv_corn:'';
    habitat_harv_corn:'';
    habitat_unharv_milo:'';
    habitat_harv_milo:'';
    habitat_unharv_beans:'';
    habitat_harv_beans:'';
    habitat_browse:'';
    ice_standing:'';
    ice_mowed:'';
    ice_disced:'';
    ice_unharv_corn:'';
    ice_harv_corn:'';
    ice_unharv_milo:'';
    ice_harv_milo:'';
    ice_unharv_beans:'';
    ice_harv_beans:'';
    ice_browse:'';
    notes:'';
    actions:'';
    response:'';
    year:'';
    time:'';
    fiscal_year:'';
}